name: my first git-hub action
on: [push]
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - run: echo "this is step 1"
  print-hello-world1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - run: echo "this is step 1"