name: my first git-hub action
on:
  push:
    branches:
      - master
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'v18'
      - name: build the project
        run: npm run build
      - name: finished 
        run: hurrySSSSSSSSSSS
 